#!/bin/sh
/bin/busybox --install -s

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "Welcome to KoreOS!"

sleep 1

#trap 'sync; /bin/busybox poweroff -f' USR2

while true; do
    echo "Starting BusyBox shell..."
    (
      USER=$(whoami)
      HOME=$(grep "^$USER:" /etc/passwd | cut -d: -f6)
      LOGNAME=$(whoami)
      HOSTNAME=$(cat /etc/hostname)
      SHELL=/bin/sh
      ENV=/root/.profile

      RED=$(printf '\033[1;31m')
      RESET=$(printf '\033[0m')

      PS1="[${RED}Kore${RESET}@${RED}KoreIso${RESET}:\w] # "

      export USER HOME LOGNAME HOSTNAME SHELL ENV PS1

      cd "$HOME"

      echo "$HOSTNAME" > /proc/sys/kernel/hostname

      echo "1 4 1 7" > /proc/sys/kernel/printk

      clear

      if [ -x /usr/bin/fastfetch ]; then
        /usr/bin/fastfetch
      fi

      /bin/busybox openvt -c 1 -w -- /bin/sh
    )

    echo "Exited Shell."

    if [ -f /tmp/shutdown ]; then
      echo "Shutting down KoreOS..."

      rm -f /tmp/shutdown
      sync

      /bin/busybox poweroff -f
    fi

    sleep 1
done
